name: Build

on: push

jobs:
  debian-10:
    runs-on: [debian-10]
    steps:
      - uses: actions/checkout@v3

      - name: Build Soup
        run: php Sun/vendor/Soup/build_lib.php

      - name: Build Sun
        run: clang -o suncli Sun/sun.cpp -ISun/vendor/Soup libsoup.a -std=c++17

      - name: Upload Sun
        uses: actions/upload-artifact@v3
        with:
          name: "Debian 10 and above"
          path: suncli
