name: Build

on: push

jobs:
  debian-10:
    runs-on: [debian-10]
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php Sun/vendor/Soup/build_lib.php

      - name: Build Sun
        run: clang -O3 -o suncli Sun/sun.cpp -ISun/vendor/Soup Sun/vendor/Soup/libsoup.a -std=c++17 -fuse-ld=lld -lstdc++ -lstdc++fs -pthreads

      - name: Upload Sun
        uses: actions/upload-artifact@v4
        with:
          name: "Debian 10 and above (X64)"
          path: suncli

      - run: php test.php

  macos-13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php Sun/vendor/Soup/build_lib.php

      - name: Build Sun
        run: clang -O3 -o suncli Sun/sun.cpp -ISun/vendor/Soup Sun/vendor/Soup/libsoup.a -std=c++17 -lc++

      - name: Upload Sun
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS (X64)"
          path: suncli

      #- run: php test.php # FIXME

  macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Build Soup
        run: php Sun/vendor/Soup/build_lib.php

      - name: Build Sun
        run: clang -O3 -o suncli Sun/sun.cpp -ISun/vendor/Soup Sun/vendor/Soup/libsoup.a -std=c++17 -lc++

      - name: Upload Sun
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS (ARM64)"
          path: suncli

      #- run: php test.php # FIXME

  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php Sun/vendor/Soup/build_lib.php

      - name: Build Sun
        run: clang -O3 -o Sun.exe Sun/sun.cpp -ISun/vendor/Soup Sun/vendor/Soup/soup.lib -std=c++17

      - name: Upload Sun
        uses: actions/upload-artifact@v4
        with:
          name: "Windows (X64)"
          path: Sun.exe

      - run: php test.php
